### PR TITLE
Update for 20.04

### PR DESCRIPTION
**Pull request by ElectrodeYT**

### CODE REVIEW

**Comment by JamiKettunen** [comment]
Please add a `clickable.yaml`:
```yaml
clickable_minimum_required: 7
builder: pure-qml-cmake
framework: ubuntu-sdk-20.04

kill: qmlscene
```

**Comment by ElectrodeYT** [comment]
> Please add a `clickable.yaml`:
> 
> ```yaml
> clickable_minimum_required: 7
> builder: pure-qml-cmake
> framework: ubuntu-sdk-20.04
> 
> kill: qmlscene
> ```

Sorry, forgot to git add it after replacing the old clickable.json file!

**Comment by delijati** [comment]
Hi guys,

i'm still on 16.04 so i would merge this "after" fosdem. I need anyway bit more time to clean it up and understand the code, bin a while since i touched this ;)

Cya

**Comment by lduboeuf** [comment]
ping @delijati  :) FOSDEM is soooon

**Comment by ElectrodeYT** [comment]
Would also like this!

**Comment by lduboeuf** [comment]
tested locally, seems to works fine :+1:

**Comment by delijati** [comment]
Uhh ahh sure will look into this :)

**Comment by delijati** [comment]
Ok it runs locally ... will merge and try to figure out how to make a release ... its bin a while :D

**Comment by lduboeuf** [comment]
> Ok it runs locally ... will merge and try to figure out how to make a release ... its bin a while :D

thanks, just doing 'clickable build` and taking the `.click` under build folder and publishing it to the openstore :)

**Comment by delijati** [comment]
Uploaded. Can someone give it a try my UT device died some years ago :/

**Comment by lduboeuf** [comment]
> Uploaded. Can someone give it a try my UT device died some years ago :/

Thank you it is installed, and woks! ;-)

**Comment by delijati** [comment]
> > Uploaded. Can someone give it a try my UT device died some years ago :/
> 
> Thank you it is installed, and woks! ;-)

So the see you then @fosdem :)

**Pull request merged**
